version: "2.3"
services:
  test:
    image: mmseg
    container_name: mmseg
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    stdin_open: true
    ipc: host
    tty: true
    privileged: true
    network_mode: "host"
    shm_size: 8g
    environment:
      - DISPLAY
      - XAUTHORITY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - $HOME/shared:/shared
    command: /bin/bash
